language: ruby
env:
  - TRAVIS=true
before_install:
  - sudo apt-get install libicu-dev -y
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
  - 2.1.5
before_script:
  - "bundle install"
script: "bundle exec rspec spec"
